### ISSUE TITLE
Randomly assigned entityname based on stopname

### ISSUE THREAD

**Issue by sebadv** [bollewolle/delijn-sensor#2]
Hi

I've noticed that there is an issue when you have 2 different stops with the same name.

My config:

```
  - platform: delijn
    api_key: "XXXXXXXXXXXXXXXXXXXX"
    next_departure:
    - stop_id: '200130'
    - stop_id: '208939'
```
Both 200130 and 208939 have the same stopname attribute 'Meersemdries, Gentbrugge'.
This resolves to a sensor entity with following name 'sensor.meersemdries_gentbrugge'

Because there are 2 of them the second one will be named 'sensor.meersemdries_gentbrugge_2'

I know that the sensor (at the start of HA) first is created as 'sensor.STOPNUMBER'. When the real stopname is loaded, the sensor gets a namechange. But which one is first is random and depending on respons time of the De Lijn API.

This results in alternating results in my case. 
![image](https://user-images.githubusercontent.com/23437866/140408728-915140cb-86aa-4783-871e-febc092bc6ee.png)

![image](https://user-images.githubusercontent.com/23437866/140408929-537cea3c-d11e-4b80-8a81-9ea28bc988ab.png)
